<?php
namespace app\admin\controller;

use app\common\model\BookCategory;
use app\common\model\BookLose;
use think\Db;

class Renwu extends Base
{
    protected $model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = Db::name('Renwu')->order("id desc")->select();
    }

    /**
     * @return \think\response\View
     * 任务列表首页
     */

    public function index(){
        $count = Db::name('Renwu')->count();
        $j = [
            'title' => "任务列表",
            'count'=>$count,
        ];
        return view("Renwu/index", $j);
    }

    /**
     * @return \think\response\Json
     * 任务列表数据
     */

    public function renwu_ajax(){
        $data = $this->model;
        foreach($data as $k=>$v){
            $data[$k]['create_time'] = date("Y-m-d",$v['create_time']);
            $data[$k]['start_time']  = date("Y-m-d",$v['start_time']);
            $img                     = $v['rw_cover'];
            $data[$k]['rw_cover']    = "<img src='$img' style='width: 100px;height: 100px;'>";
            $data[$k]['rw_cat']      = Db::name('cat')->where(['id'=>$v['rw_cat']])->value('cat_name');
            switch ($v['rw_status']){
                case 0:
                    $status = "<span class=\"label label-defaunt radius\">未支付佣金</span>";
                    break;
                case 1:
                    $status = "<span class=\"label label-success radius\">已支付佣金</span>";
                    break;
                case 2:
                    $status = "<span class=\"label label-defaunt radius\">未被接单</span>";
                    break;
            }
            $data[$k]['rw_status'] = $status;

            switch ($v['is_show']){
                case 0:
                    $is_show ="<span class=\"label label-defaunt radius\">未发布</span>" ;
                    break;
                case 1:
                    $is_show = "<span class=\"label label-success radius\">已发布</span>";
                    break;

            }
            $data[$k]['is_show'] = $is_show;
            $id = $v['id'];
            $name = $v['is_show'] == 0 ? "发布" : "取消发布";
            $data[$k]['caozuo'] = "<a onclick=\"rw_fb(this,$id)\" id='fb'>$name</a> | <a style=\"text-decoration:none\" onclick=\"rw_rm(this,$id)\">推荐热门</a>
 | <a href=\"/admin/Renwu/read?id=$id\" title=\"编辑\"><i class=\"Hui-iconfont\" >&#xe6df;</i></a> | 
 <a style=\"text-decoration:none\" class=\"ml-5\" onClick=\"rw_del(this,$id)\" href=\"javascript:;\" title=\"删除\"><i class=\"Hui-iconfont\">&#xe6e2;</i></a>";

            $data[$k]['rw_hot'] = $v['rw_hot'] == 0 ? "<span class=\"label label-defaunt radius\">非热门任务</span>" : "<span class=\"label label-success radius\">热门任务</span>";
        }
        return json(['data'=>$data]);
    }

    /**
     * @return \think\response\Json
     * 推荐热门
     */

    public function remen(){
        $id     = input('id');
        $is_hot = input('is_hot');

        $s = Db::name('Renwu')->where(['id'=>$id])->update([
            'rw_hot'=>$is_hot
        ]);

        if($s){
            $msg['code'] = 200;
            $msg['msg']  = "操作成功";
        }else{
            $msg['code'] = 200;
            $msg['msg']  = "数据无变化";
        }

        return json($msg);
    }


    public function read(){
        $id = input('id');
        $data = Db::name('Renwu')->where(['id'=>$id])->find();

//        var_dump($data);die;
        $font = "style=\"font-size:14px\"";
        switch ($data['rw_status']){
            case 0:
                $status = "<span class=\"label label-defaunt radius\" $font>未支付佣金</span>";
                break;
            case 1:
                $status = "<span class=\"label label-success radius\" $font>已支付佣金</span>";
                break;
            case 2:
                $status = "<span class=\"label label-defaunt radius\" $font>未被接单</span>";
                break;
        }
        $data['rw_status'] = $status;

        switch ($data['rw_pass']){
                case 0:
                    $pass = "<span class=\"label label-defaunt radius\" $font>未审核</span>";
                    break;
                case 1:
                    $pass = "<span class=\"label label-defaunt radius\" $font>审核未通过</span>";
                    break;
                case 2:
                    $pass = "<span class=\"label label-success radius\" $font>审核已通过</span>";
                    break;
            }

        $data['rw_pass'] = $pass;
        $data['rw_img']  = json_decode($data['rw_img'],true);
        $data['create_time'] = date('Y-m-d',$data['create_time']);
        $data['start_time'] = date('Y-m-d',$data['start_time']);
        //省份
        $province = Db::name('HatProvince')->select();

        //城市
        $city = Db::name('HatCity')->where(['father'=>Db::name('HatCity')->where(['city'=>$data['rw_area']])->value('father')])->select();

        //任务属性
        $rw_cat = Db::name('Cat')->field('id,cat_name')->where(['level'=>2])->select();
        $j = [
            'title'=>"任务详情",
            'data'=>$data,
            'province'=>$province,
            'rw_cat'=>$rw_cat,
            'city'=>$city
        ];
        return view('Renwu/add',$j);
    }


    /**
     * 任务图片处理
     */

    /*public function img(){
        if ((request()->file('file')) != NULL) {
            $file = request()->file('file');
            // 移动到框架应用根目录/public/uploads/ 目录下
            $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads');
            $img = '/uploads/' . $info->getSaveName();
            if(session('rw_img') == ""){
                session('rw_img',$img);
            }else{
                $iimg = session('rw_img').','.$img;
                session('rw_img',$iimg);
            }
        }
    }*/


    /**
     * @return string
     * 操作任务 数据
     */

    public function add(){
        $id         = input('id');
        $data['rw_title']               = input('rw_title');
        $data['rw_yj']                  = input('rw_yj');
        $data['rw_ding']                = input('rw_ding');
        $data['rw_main']                = input('rw_main');
        $data['create_time']            = strtotime(input('create_time'));
        $data['start_time']             = strtotime(input('start_time'));
        $data['rw_province']             = Db::name('HatProvince')->where(['provinceID'=>input('rw_provice')])->value('province');
        $data['rw_city']                = input('rw_city');
        $data['rw_cat']                 = input('rw_cat');

        $data['rw_area']                = $data['rw_city'];
        $data['pay_limit_time']         = input('pay_limit_time');
//        unset($data['rw_provice']);
        unset($data['rw_city']  );
        if (!is_numeric($data['rw_yj'])|| !is_numeric($data['rw_ding']) || !is_numeric($data['pay_limit_time']) )
        {
            return "<script>alert('请填写正确的任务金额或任务时间');setTimeout(function() {
                    history.go(-1)
                    },500)</script>";
        }

        if (preg_match("/^[\x{4e00}-\x{9fa5}]+$/u",$data['rw_title'])) {

        } else {
            return "<script>alert('任务名称只能为汉字');setTimeout(function() {
                    history.go(-1)
                    },500)</script>";
        }





        if ((request()->file('rw_cover')) != NULL) {
            $file = request()->file('rw_cover');
            // 移动到框架应用根目录/public/uploads/ 目录下
            $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads');
            $data['rw_cover'] = '/uploads/' . $info->getSaveName();
        }

        if(request()->file('rw_img') !=NULL){
            $files = request()->file('rw_img');
            foreach($files as $file){
                // 移动到框架应用根目录/public/uploads/ 目录下
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads');
                if($info){
                    $rw_img[] = DS.'uploads'.DS.$info->getSaveName();
                }else{
                    // 上传失败获取错误信息
                    echo $file->getError();
                }
            }
        }



        if(empty($id)){
            $data['rw_status'] = 2;

            $data['rw_img'] = empty($rw_img) ? '':json_encode($rw_img);
            $s = Db::name('Renwu')->insert($data);

            if($s){
                return "<script>alert('添加成功');setTimeout(function() {
                    history.go(-1)
},500)</script>";
            }else{
                return "<script>alert('修改失败');setTimeout(function() {
                    history.go(-1)
},500)</script>";
            }
        }else{
            $img = Db::name('Renwu')->where(['id'=>$id])->value('rw_img');
            if(!empty($img)) {
                $img = json_decode($img, true);
                if(!empty($rw_img)){
                    $rw_img = array_merge($rw_img,$img);
                }
            }

            $rw_img = empty($rw_img) ? $img : $rw_img;

            $data['rw_img'] = json_encode($rw_img);

            $status = Db::name('Renwu')->where(['id'=>$id])->value('rw_status');

            if($status != 2){
                return "<script>alert('任务已被接单 无法修改');setTimeout(function() {
                    history.go(-1)
},500)</script>";
            }else{
                $s = Db::name('Renwu')->where(['id'=>$id])->update($data);
                if($s){
                    return "<script>alert('修改成功');setTimeout(function() {
                    history.go(-1)
},500)</script>";
                }else{
                    return "<script>alert('修改失败');setTimeout(function() {
                    history.go(-1)
},500)</script>";
                }
            }
        }
    }



    /**
     * @return \think\response\View
     * 新增任务页面
     */

    public function add_rw(){
        $font = "style=\"font-size:14px\"";
        $status = "<span class=\"label label-defaunt radius\" $font>未支付佣金</span>";
        $data['rw_status'] = $status;

        $pass = "<span class=\"label label-defaunt radius\" $font>未审核</span>";
        $data['rw_pass'] = $pass;


        $data['rw_img']         = array();
        $data['rw_title']       = "";
        $data['rw_yj']          = "";
        $data['rw_ding']        = "";
        $data['rw_cat']         = "";
        $data['rw_main']        = "";
        $data['rw_province']    = "";
        $data['rw_area']        = "";
        $data['rw_cover']       = "";
        $data['create_time']    = date('Y-m-d',time());
        $data['start_time']     = date('Y-m-d',time());
        $data['pay_limit_time']  = "";
        $data['id']  = "";
        $province = Db::name('HatProvince')->select();

        $city = Db::name('HatCity')->where(['father'=>Db::name('HatCity')->where(['city'=>$data['rw_area']])->value('father')])->select();

        $rw_cat = Db::name('Cat')->field('id,cat_name')->where(['level'=>2])->select();
        $j = [
            'title'     =>"新增任务",
            'data'      =>$data,
            'province'  =>$province,
            'rw_cat'    =>$rw_cat,
            'city'      =>$city
        ];
        return view('Renwu/add',$j);
    }


    /**
     * @return \think\response\Json
     * 删除任务
     */

    public function rw_del(){
        $id = input('id');
        $s = Db::name('Renwu')->where(['id'=>$id])->delete();
        if($s){
            $code = 200;
        }else{
            $code = 404;
        }

        return json($code);
    }

    /**
     * @return \think\response\Json
     * 任务发布
     */

    public function fabu(){
        $id = input('id');
        $is_pass = Db::name('Renwu')->where(['id'=>$id])->value('is_show') == 1 ? 0 : 1;

        $s = Db::name('Renwu')->where(['id'=>$id])->update(['is_show'=>$is_pass]);
        if($s){
            $code = 200;
        }else{
            $code = 404;
        }


        return json($code);
    }

    public function area(){
        $father = input('father');
        $data = Db::name('HatCity')->where(['father'=>$father])->field('city,cityID')->select();

        return json($data);
    }


    public function cat(){
        $j = [
            'title'=>'任务分类'
        ];

        return view('Renwu/cat',$j);
    }

    public function cat_ajax(){
        $data = Db::name('Cat')->where(['level'=>1])->select();
        foreach($data as $k=>$v){
            $id                         = $v['id'];
            $data[$k]['cat_type']       = "一级分类";
            $img                        = $v['cat_img'];
            $data[$k]['cat_img']        = "<img src='$img' style='width: 80px;height: 80px'>";


            $data[$k]['caozuo'] = "<a onclick='cat_sec($id)'>查看二级分类</a> | <a onclick='cat_update($id)'><i class=\"Hui-iconfont\" >&#xe6df;</i></a> | 
 <a style=\"text-decoration:none\" class=\"ml-5\" onClick=\"cat_del(this,$id)\" href=\"javascript:;\" title=\"删除\"><i class=\"Hui-iconfont\">&#xe6e2;</i></a>";

        }

        return json(['data'=>$data]);
    }


    /**
     * @return \think\response\Json
     * 删除任务分类属性
     */
    public function cat_del(){
        $id = input('id');
        $check = Db::name('Cat')->where(['p_id'=>$id])->find();
        if(empty($check)){
            $s = Db::name('Cat')->where(['id'=>$id])->delete();
            if($s){
                $code = 200;
            }
        }else{
            $code = 404;
        }



        return json($code);
    }

    /**
     * @return \think\response\View
     * 二级分类
     */

    public function sec(){
        $id     = input('id');
        $data   = Db::name('Cat')->where(['p_id'=>$id])->field('cat_name,id')->select();
        $f_name = Db::name('Cat')->where(['id'=>$id])->value('cat_name');
        $j = [
            'title'=>'二级分类',
            'data'=>$data,
            'f_name'=>$f_name
        ];

        return view('Renwu/sec',$j);
    }


    public function fir(){
        $id = input('id');
        $data = Db::name('Cat')->where(['id'=>$id])->find();

        $j= [
            'title'=>'编辑分类',
            'data'=>$data
        ];

        return view('Renwu/edit',$j);
    }


    public function save(){
        $id                 = input('id');
        $data               = input('post.');

//         var_dump($data);die;
        if($id ==0){
            $data['create_time']        = time();
            $data['pro_img']            = session('cat_img');
            $s = Db::name('Cat')->insert($data);
        }else{
            $data['cat_img']    = session('cat_img') ==  " " ? Db::name('Cat')->where(['id'=>$id])->value('cat_img') : session('cat_img');
            $s = Db::name('Cat')->where(['id'=>$id])->update([
                'cat_name'=>$data['cat_name'],
                'cat_img'=>$data['cat_img'],
            ]);

        }
        if($s){
            $code = 200;
        }else{
            $code = 404;
        }
        return json($code);
    }


    /**
     * @return \think\response\Json
     * 删除二级分类
     */

    public function sec_del(){
        $id = input('id/a');
        if($id == NULL){
            $msg['code'] = 405;
            $msg['msg']  = "该分类下没有二级分类,删除失败";
        }else{
            foreach($id as $k=>$v){
                $check = Db::name('Renwu')->where(['rw_cat'=>$v])->find();
                if(empty($check)){
                    $code = 200;
                    continue;
                }else{
                    $code = 403;
                    break;
                }
            }

            if($code == 200){
                foreach($id as $k=>$v){
                    Db::name('Cat')->where(['id'=>$v])->delete();
                }

            }else{
                $msg['code'] = 403;
                $msg['msg']  = "该属性下有任务,删除失败";
            }
        }

        return json($msg);
    }


    public function add_cat(){
        $id = input('id');
        if($id == 0){
            $fir['id']          = 0;
            $fir['cat_name']    = "";
            $fir['cat_img']     = "";
            $sec[0]['id']       = 0;
            $sec[0]['cat_name'] = "";
            $sec[0]['p_id']     = 0;
            $f = 0;
        }else{
            $fir = Db::name('Cat')->field('id,cat_name,cat_img')->where(['id'=>$id])->find();
            $sec = Db::name('Cat')->field('id,cat_name,p_id')->where(['p_id'=>$id])->select();

            if(empty($sec)){
                $sec[0]['id']       = 0;
                $sec[0]['cat_name'] = "";
                $sec[0]['p_id']     = $fir['id'];
            }
            $f = 1;
        }
        $data = Db::name('Cat')->where(['level'=>1])->select();
        $j = [
            'title'=>'添加属性',
            'data'=>$data,
            'fir'=>$fir,
            'sec'=>$sec,
            'f'=>$f
        ];

        return view('Renwu/cat_add',$j);
    }


    public function cat_save(){
        $data = input('post.');
        if($data['f'] == 0){
            unset($data['f']);
            if(!empty($data['fcat_name']) || !empty($data['scat_name'])){
                if($data['type'] == 0){

                    //二级分类
                    unset($data['fcat_name']);
                    unset($data['type']);
                    $data['level'] = 2;
                    $data['cat_name'] = $data['scat_name'];
                    unset($data['scat_name']);

                }else{

                    //一级分类
                    unset($data['scat_name']);
                    unset($data['type']);
                    unset($data['p_id']);
                    $data['level'] = 1;
                    $data['p_id'] = 0;
                    $data['cat_name'] = $data['fcat_name'];
                    unset($data['fcat_name']);
                    $data['cat_img']   = session('cat_img');
                }

                $data['create_time'] = time();
                $s = Db::name('Cat')->insert($data);
                if($s){
                    $code = 200;
                }
            }
        }


        return json($code);
    }
}
